### ISSUE TITLE
Epic: Customer Reviews

### ISSUE THREAD

**Issue by Bryaro** [Bryaro/pp5#10]
**As a** customer,  
**I want** to be able to review products, see others reviews and edit my review,  
**so that** I can see others' reviews I can share my experience with other potential buyers and contribute to the community.

User Story 9: **Adding Product Reviews**

#### Tasks
- [x] Add a button or link to guide customers reviews
- [x] create a new app in django and add the models for it
- [x]  make templates and style, and test their functions
