### ISSUE TITLE
Admin User Story 12: Adding Products

### ISSUE THREAD

**Issue by Bryaro** [Bryaro/pp5#12]
### User Story 1: Adding Products
**As an** admin,  
**I would like** to be able to view exactly as user and add new products to the website and edit button under add to cart button,  
**so that** I can expand the product offerings available to customers.

#### Acceptance Criteria
- **Given** I am logged in as an admin,  also be able to view as a user and add new products to the website and edit button under the add to cart button,
- **When** I navigate to the "Add Product/manage products/dashboard" page,
- **Then** I can fill out a form with product details (name, price, image, etc.) and submit it to add the product to the website and can quickly view it as an user.

#### Tasks
- [x] Design and implement the "Add Product" page layout.
- [x] Create a form on the "Add Product" page for product details (name, price, image upload, description, etc.).
- [x] Implement backend functionality to process the form data and add the product to the database.
- [x] Test the "Add Product" feature to ensure products are correctly added to the website.
