### ISSUE TITLE
User story as Admin: Create blog

### ISSUE THREAD

**Issue by Bryaro** [Bryaro/pp5#18]
As a **Superuser**, I would like **to be able to create new blog posts**, so that **I can share content with users**.

### Acceptance Criteria:
- Acceptance Criteria 1
    **Given** that I am a superuser
    **When** I navigate to the create post interface
    **Then** I can create a new blog post.

- Acceptance Criteria 2
    **Given** that I am a superuser
    **When** I create a new blog post
    **Then** the post is visible to all registered and visitor users on the homepage.

- Acceptance Criteria 3
    **Given** that I am a superuser
    **And**, I want to create a new post
    **When** I submit the create post form
    **Then** the new post is successfully added to the app.

### Tasks
- [x] Task 1 – Develop an interface for superusers to create new blog posts
- [x] Task 2 – Implement functionality to add new blog posts to the database
- [x] Task 3 – Ensure newly created posts are displayed on the homepage for all users.
