### ISSUE TITLE
User story: View Blog and comment as registered user

### ISSUE THREAD

**Issue by Bryaro** [Bryaro/pp5#19]
As a **User**, I would like **to be able to view blog posts**, so that **I can stay updated with the latest content**.

### Acceptance Criteria:
- Acceptance Criteria 1
    **Given** that I am a user
    **When** I navigate to the homepage with button or link to blog
    **Then** I can see a feed of the latest blog posts.

- Acceptance Criteria 2
    **Given** that I am viewing a blog post
    **When** I click on the post
    **Then** I can view its full content along with comments.

- Acceptance Criteria 3
    **Given** that I am a registered user
    **And** I am viewing a blog post
    **And** I want to leave a comment
    **When** I submit a comment
    **Then** my comment is displayed below the blog post.

- Acceptance Criteria 4
    **Given** that I am not a registered user
    **And** I attempt to leave a comment on a blog post
    **When** I submit a comment
    **Then** I am redirected to the login page.

### Tasks
- [x] Task 1 – Develop a homepage with a feed of blog posts
- [x] Task 2 – Implement navigation to view full content of a blog post
- [x] Task 3 – Develop a comment submission form
- [x] Task 4 – Implement functionality to display comments below blog posts
