### ISSUE TITLE
User Story 2: Searching for Products

### ISSUE THREAD

**Issue by Bryaro** [Bryaro/pp5#3]
**As a** Customer,  
**I would like** to use the search bar to find specific types of watches or accessories,  
**so that** I can find exactly what I am looking for quickly.

#### Acceptance Criteria
- **Given** that I am looking for a specific type of watch or accessory
- **When** I use the search bar
- **Then** I am presented with relevant search results, with options to sort them by price, and rating.

#### Tasks
- [x] Integrate a search bar in the website header.
- [x] Create search functionality to filter products based on keywords.
- [x] Implement sorting options for search results (price, popularity, new arrivals).
