### ISSUE TITLE
User Story 5: Accessing Customer Support ( wont-have, but will add for future plan )

### ISSUE THREAD

**Issue by Bryaro** [Bryaro/pp5#6]
**As a** Customer,  
**I would like** to find easily accessible customer support options while shopping,  
**so that** I can get contact/ or assistance if I need it.

#### Acceptance Criteria
- **Given** that I require assistance with my shopping
- **When** I look for customer support options
- **Then** I find easily accessible customer support, including FAQs, live chat, and email support.

#### Tasks
- [ ] Set up a FAQ section with common questions and answers.
- [ ] Integrate live chat support using a third-party service.
- [ ] Provide email support and create a system for managing customer inquiries.
